### ISSUE TITLE
I dont have my personal proxxy.

### ISSUE THREAD

**Issue by Abdul-Ahad-Supto** [zemetsskiy/ZealyAutomatization#11]
My guy I cant solve the IP:port:username:password problem. I use a local internet to browse

**Comment by zemetsskiy** [comment]
bro soft doesnt work with your ip address. u can buy proxies for a small price (<1.5$) everywhere on the internet. ( ex https://proxy6.net/ )

**Comment by Abdul-Ahad-Supto** [comment]
Thanks bro. As a programmer I loved your code. Great work. Much
appreciated. If you don't mind can I ask if you have a personal
discord server? Or something like that?or do you stream. I want to learn
from you. Im studying Computer Science and Im on my 2nd year. Thanks

**Comment by zemetsskiy** [comment]
really appreciate your feedback man

**Comment by zemetsskiy** [comment]
really appreciate your feedback dude, I dont have a personal discord server and I dont stream either. u can dm me in telegram if u need sth @zemetsskiy

**Comment by Abdul-Ahad-Supto** [comment]
Solved
